# This is a basic workflow to help you get started with Actions

name: CI

on: [push]

jobs:
  scan:
    runs-on: ubuntu-20.04
    steps:
     - name: Checkout
       uses: actions/checkout@v2
     - name: Set up JDK 11
       uses: actions/setup-java@v2
       with:
          java-version: '11'
          distribution: 'adopt'
          cache: maven
     - name: Perform Scan
       uses: ShiftLeftSecurity/scan-action@master
       with:
         type: "credscan,Java,depscan"
       env:
         WORKSPACE: https://github.com/${{ github.repository }}/blob/${{ github.sha }}
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

     - uses: actions/upload-artifact@v1
       with:
         name: reports
         path: reports

